-- Create enum for admin roles
CREATE TYPE public.app_role AS ENUM ('super_admin', 'admin');

-- Create user_roles table for admin access management
CREATE TABLE public.user_roles (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE NOT NULL,
  role app_role NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  UNIQUE (user_id, role)
);

-- Enable RLS on user_roles
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;

-- Create security definer function to check if user has a specific role
CREATE OR REPLACE FUNCTION public.has_role(_user_id UUID, _role app_role)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id
      AND role = _role
  )
$$;

-- Create function to check if user is any admin
CREATE OR REPLACE FUNCTION public.is_admin(_user_id UUID)
RETURNS BOOLEAN
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1
    FROM public.user_roles
    WHERE user_id = _user_id
      AND role IN ('super_admin', 'admin')
  )
$$;

-- RLS policies for user_roles table
CREATE POLICY "Admins can view all roles"
ON public.user_roles
FOR SELECT
TO authenticated
USING (public.is_admin(auth.uid()));

CREATE POLICY "Super admins can insert roles"
ON public.user_roles
FOR INSERT
TO authenticated
WITH CHECK (public.has_role(auth.uid(), 'super_admin'));

CREATE POLICY "Super admins can delete roles"
ON public.user_roles
FOR DELETE
TO authenticated
USING (public.has_role(auth.uid(), 'super_admin'));

-- Create the app_users table for student registrations
CREATE TABLE public.app_users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  surname TEXT,
  gname TEXT,
  dob DATE,
  age INT,
  school TEXT,
  email TEXT,
  religion TEXT,
  baptized TEXT,
  communion TEXT,
  confirmation TEXT,
  section TEXT,
  allotment TEXT,
  block TEXT,
  house_number TEXT,
  road TEXT,
  unit TEXT,
  suburban TEXT,
  father_name TEXT,
  father_occupation TEXT,
  employer_name TEXT,
  place_of_origin TEXT,
  contact_number TEXT,
  father_email TEXT,
  mother_name TEXT,
  mother_occupation TEXT,
  mother_employer_name TEXT,
  mother_place_of_origin TEXT,
  mother_contact_number TEXT,
  mother_email TEXT,
  guardian_name TEXT,
  guardian_occupation TEXT,
  guardian_relationship TEXT,
  guardian_place_of_origin TEXT,
  guardian_contact_number TEXT,
  guardian_email TEXT,
  emergency_contact_name TEXT,
  emergency_relationship TEXT,
  emergency_contact_number TEXT,
  transport TEXT,
  mode TEXT,
  agree_transport TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable RLS on the app_users table
ALTER TABLE public.app_users ENABLE ROW LEVEL SECURITY;

-- Anyone can insert (public registration form)
CREATE POLICY "Anyone can submit registration"
ON public.app_users
FOR INSERT
WITH CHECK (true);

-- Only admins can view registrations
CREATE POLICY "Admins can view all registrations"
ON public.app_users
FOR SELECT
TO authenticated
USING (public.is_admin(auth.uid()));

-- Only super admins can update registrations
CREATE POLICY "Super admins can update registrations"
ON public.app_users
FOR UPDATE
TO authenticated
USING (public.has_role(auth.uid(), 'super_admin'));

-- Only super admins can delete registrations
CREATE POLICY "Super admins can delete registrations"
ON public.app_users
FOR DELETE
TO authenticated
USING (public.has_role(auth.uid(), 'super_admin'));